name: tudu
description: "A new Flutter project."

publish_to: "none" 

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.15.2
  firebase_auth: ^5.7.0
  get_it: ^8.0.3
  equatable: ^2.0.7
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  meta: ^1.16.0
  flutter_screenutil: ^5.9.3
  google_fonts: ^6.2.1
  avatars: ^3.0.2
  talker: ^5.0.2
  talker_flutter: ^5.0.2
  table_calendar: ^3.2.0
  intl: ^0.20.2
  dropdown_button2: ^2.3.9
  clipboard: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/

